# Project configuration
site_name: FAIRagro Knowledgebase
site_url: https://fairagro.github.io/knowledgebase
copyright: Copyright &copy; 2025 FAIRagro

# Navigation Header Deutsch (English Override -> language settings)
nav:
    - Home: index.de.md
    - Grundlagen des FDM: basics.de.md
    - Agrarspezifisches FDM:
        - Agrarspezifische Daten: rdm/specific_data.de.md
        - Repositorien: rdm/data_repositories.de.md
        - FAIRe Code-Veröffentlichung: rdm/fair_code.de.md
        - Recht im FDM: rdm/legal.de.md
        - Leitfaden Data Handling: rdm/data_handling.de.md
        - Leitfaden Projekt Planung: rdm/project_planning.de.md
    - Trainingsmaterialien: training_material.de.md
    - FAIRagro Tools & Services: tools.de.md
    - Sonstiges: 
        - Interessante Projekte: projects.de.md
        - Links: links.md
    - zur FAIRagro Website: https://fairagro.net


# Theme configuration
theme:
    name: material
    logo: assets/logo.png
    favicon: assets/favicon.png
    font: false
    features:
        # navigation
        - navigation.tabs
        - navigation.tabs.sticky
        - navigation.path
        - navigation.sections
        - navigation.indexes
        - navigation.top 
        - navigation.tracking
        # toc
        - toc.integrate 
        - toc.follow
    #color scheme
    palette:
        primary: green
        accent: amber

# Language settings
plugins:
  - search
  - i18n:
      reconfigure_material: true
      reconfigure_search: true
      docs_structure: suffix
      languages:
        - locale: de
          default: true
          name: Deutsch
          build: true
        - locale: en
          name: English
          build: true
          # English navigation
          nav:
            - Home: index.en.md
            - RDM Basics: basics.en.md
            - Agriculture-specific RDM:
                - Agriculture-specific Data: rdm/specific_data.en.md
                - Repositories: rdm/data_repositories.en.md
                - Publishing Code FAIR: rdm/fair_code.en.md
                - Legal topics in RDM: rdm/legal.en.md
                - Guideline Data Handling: rdm/data_handling.en.md
                - Guideline Project Planning: rdm/project_planning.en.md
            - Training Material: training_material.en.md
            - FAIRagro Tools & Services: tools.en.md
            - Other: 
                - Interesting Projects: projects.en.md
                - Links: links.en.md
            - to the FAIRagro Website: https://fairagro.net/en

markdown_extensions:
  - attr_list
  - footnotes
