# Project configuration
site_name: FAIRagro Knowledgebase
site_url: https://fairagro.github.io/knowledgebase
copyright: Copyright &copy; 2025 FAIRagro

# Navigation Header
nav:
    - Home: index.md
    - FDM Themen:
        - FDM allgemein: general.md
        - Agrarspezifische Daten: specific_data.md
        - Repositorien: data_repositories.md
        - Recht im FDM: legal.md
    - Guidelines:
        - Leitfaden Data Handling: guidelines/data_handling.md
        - Leitfaden Projekt Planung: guidelines/project_planning.md
    - Trainingsmaterialien: training_material.md
    - Sonstiges: 
        - Interessante Projekte: projects.md
        - Links: links.md
    - FAIRagro Website: https://fairagro.net

# Theme configuration
theme:
    name: material
    logo: assets/logo.png
    favicon: favicon.ico
    features:
        # navigation
        - navigation.tabs
        - navigation.tabs.sticky
        - navigation.path
        - navigation.sections
        - navigation.indexes
        - navigation.top 
        - navigation.tracking
        # toc
        - toc.integrate 
        - toc.follow
